@echo off
echo Running Prisma DB Push...
call npx prisma db push --accept-data-loss > prisma_push_out.txt 2>&1
echo Running Prisma Generate...
call npx prisma generate > prisma_gen_out.txt 2>&1
echo Running Seed...
call npx prisma db seed > prisma_seed_out.txt 2>&1
echo Done.
